apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bandeja-extendida
  description: Artist main website
spec:
  type: website
  lifecycle: production
  owner: team-a
  system: carpeta-fiscal
